name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Create .env file
      run: |
        echo "PORT=80" > .env
    
    - name: Build
      run: go build -o poc-api-deploy-production-golang ./src/  

